services:
  postgres:
    image: postgres:16-alpine
    container_name: ig_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ig_tracker
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: Backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ig_tracker
      INSTAGRAM_APP_ID: ${INSTAGRAM_APP_ID}
      INSTAGRAM_APP_SECRET: ${INSTAGRAM_APP_SECRET}
      IG_SESSION_ID: ${IG_SESSION_ID}
      IG_CSRF_TOKEN: ${IG_CSRF_TOKEN}
      CRON_SECRET: ${CRON_SECRET}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    volumes:
      - ./backend:/app
      - /app/.venv  
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./.env


volumes:
  pg_data:
